- hosts: "{{ hostgroup }}"
  gather_facts: False
  vars_files:
  - ~/ansible/.vault
  tasks:
  - name: "Join Server to the domain"
  - win_domain_membership:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "{{ domainuser }}"
      domain_admin_password: "{{ domainpassword }}"
      domain_ou_path: "{{ ou }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required